name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Fix Track entity SQL issue
      run: |
        cd backend
        # Find Track.java and fix the "key" field which is a SQL reserved keyword
        find src/main/java -name "Track.java" -type f -exec sed -i 's/@Column(nullable = false)\\s*private String key;/@Column(name = "music_key")\\n    private String key;/g' {} \;
    
    - name: Set up test resources
      run: |
        cd backend
        mkdir -p src/test/resources
        mkdir -p src/test/java/com/tunelar/backend/config
        
        # Create simplified TestSecurityConfig
        cat > src/test/java/com/tunelar/backend/config/TestSecurityConfig.java << 'EOF'
        package com.tunelar.backend.config;

        import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
        import org.springframework.context.annotation.Bean;
        import org.springframework.context.annotation.Configuration;
        import org.springframework.context.annotation.Primary;
        import org.springframework.context.annotation.Profile;
        import org.springframework.security.config.annotation.web.builders.HttpSecurity;
        import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
        import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
        import org.springframework.security.config.annotation.web.configurers.HeadersConfigurer;
        import org.springframework.security.core.userdetails.User;
        import org.springframework.security.core.userdetails.UserDetails;
        import org.springframework.security.core.userdetails.UserDetailsService;
        import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
        import org.springframework.security.crypto.password.PasswordEncoder;
        import org.springframework.security.provisioning.InMemoryUserDetailsManager;
        import org.springframework.security.web.SecurityFilterChain;

        @Configuration
        @EnableWebSecurity
        @Profile("test")
        public class TestSecurityConfig {

            @Bean
            public PasswordEncoder passwordEncoder() {
                return new BCryptPasswordEncoder();
            }

            @Bean
            @Primary
            public UserDetailsService userDetailsService() {
                UserDetails adminUser = User.builder()
                        .username("admin")
                        .password(passwordEncoder().encode("admin123"))
                        .roles("ADMIN")
                        .build();
                
                UserDetails modUser = User.builder()
                        .username("mod")
                        .password(passwordEncoder().encode("password"))
                        .roles("MOD")
                        .build();
                
                UserDetails prodUser = User.builder()
                        .username("prod")
                        .password(passwordEncoder().encode("password"))
                        .roles("PROD")
                        .build();
                
                return new InMemoryUserDetailsManager(adminUser, modUser, prodUser);
            }

            @Bean
            @Primary
            @ConditionalOnMissingBean
            public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
                http
                    .csrf(AbstractHttpConfigurer::disable)
                    .headers(headers -> headers.frameOptions(HeadersConfigurer.FrameOptionsConfig::disable))
                    .authorizeHttpRequests(auth -> 
                        auth.anyRequest().permitAll()
                    );
                
                return http.build();
            }
        }
        EOF
        
        # Create simplified application-test.properties
        cat > src/test/resources/application-test.properties << EOF
        # Use H2 in-memory database with a random name to avoid conflicts across test runs
        spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        spring.datasource.username=sa
        spring.datasource.password=
        spring.datasource.driver-class-name=org.h2.Driver

        # JPA Configuration
        spring.jpa.hibernate.ddl-auto=create-drop
        spring.jpa.show-sql=false
        spring.jpa.properties.hibernate.format_sql=false
        spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

        # JWT Configuration
        app.jwt-secret=test-jwt-secret-key-for-unit-tests-only
        app.jwt-expiration-milliseconds=3600000

        # Admin password for test
        app.admin-user-password=admin123

        # Allow bean definition overriding for testing
        spring.main.allow-bean-definition-overriding=true

        # Disable security auto configuration
        spring.security.user.name=testuser
        spring.security.user.password=testpass

        # Reduce logging to make test output cleaner
        logging.level.root=WARN
        logging.level.org.springframework=ERROR
        logging.level.org.hibernate=ERROR
        logging.level.com.tunelar=INFO

        # Set fixed name for test app
        spring.application.name=tunelar-test
        EOF
    
    - name: Build with Maven (skip tests)
      run: |
        cd backend
        ./mvnw -B clean package -DskipTests
      env:
        MAVEN_OPTS: "-Xmx2048m"
    
    - name: Run Simple Test First
      run: |
        cd backend
        # Create a simple test class that just checks if context loads
        mkdir -p src/test/java/com/tunelar/backend
        cat > src/test/java/com/tunelar/backend/SimpleTest.java << 'EOF'
        package com.tunelar.backend;

        import org.junit.jupiter.api.Test;
        import org.springframework.boot.test.context.SpringBootTest;
        import org.springframework.test.context.ActiveProfiles;

        @SpringBootTest
        @ActiveProfiles("test")
        public class SimpleTest {
            @Test
            public void contextLoads() {
                // This test will just check if the application context loads
            }
        }
        EOF
        # Run just this test to see if context loads
        ./mvnw -B test -Dtest=SimpleTest -Dspring.profiles.active=test
      env:
        MAVEN_OPTS: "-Xmx2048m"
    
    - name: Run All Tests
      run: |
        cd backend
        ./mvnw -B test -Dspring.profiles.active=test
      env:
        MAVEN_OPTS: "-Xmx2048m"
    
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: backend-test-reports
        path: backend/target/surefire-reports