name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: tunelar_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build with Maven (skip tests)
      run: |
        cd backend
        ./mvnw -B clean package -DskipTests -Dspring.profiles.active=ci
      env:
        MAVEN_OPTS: "-Xmx2048m"
    
    - name: Run Tests
      run: |
        cd backend
        ./mvnw -B test -Dspring.profiles.active=ci -Dspring.datasource.url=jdbc:mysql://localhost:3306/tunelar_test -Dspring.datasource.username=root -Dspring.datasource.password=${{ secrets.DB_PASSWORD }}
      env:
        MAVEN_OPTS: "-Xmx2048m"
