name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Using Node.js 16 to avoid OpenSSL issues
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    # If you need to use Node.js 18+, uncomment this step
    - name: Set NODE_OPTIONS environment variable
      run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/build